import = [
    "~/.config/alacritty/themes/themes/rose-pine-moon.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "None"

opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
#normal.family = "MesloLGS Nerd Font Mono"

size = 10

[shell]
program = "/bin/zsh"
